### ISSUE TITLE
Function about visualization

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/2023-DSCI522-Group22#10]
Hello team, I am working on converting a visualization to a function. But I wonder how to test it. It seems that it is not possible to test if a chart is bar chart or scatter plot. Any ideas?

**Comment by lichunubc** [comment]
Altair will create an object, which will produce many of its properties with the right command. You can check the autograder scripts from DSCI 531

**Comment by jinyz8888** [comment]
Will do it. Thanks!

**Comment by jinyz8888** [comment]
Solved
