### ISSUE TITLE
Minor update to repo organization

### ISSUE THREAD

**Issue by lichunubc** [UBC-MDS/2023-DSCI522-Group22#12]
We will move the analysis ipynb file into a new folder called `notebook`. The `src` folder will now house all the custom function scripts and we will make another new folder `tests` to house all the pytest scripts.

I have seen this kind of organization from a number of other repos and it seems to be a standard way for good practices. Please let me know if this is a good idea.

**Comment by jcairn02** [comment]
If it's a standard good practise , lets do it!

**Comment by jinyz8888** [comment]
Agree!
