### ISSUE TITLE
Branch naming conventions

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/2023-DSCI522-Group22#17]
Hey all!
Relatively minor thing, but wanted to remind everyone to name their branches after the functionality type of their update and some sort of version code or time stamp to differentiate new branches from old branches.
It was mentioned in class and we confirmed later it will effect our grades.

**Comment by jinyz8888** [comment]
Thanks for reminding:). How about I change my branch to be func_wine_prediction_chart_v1?

**Comment by jinyz8888** [comment]
Renamed it! :)
