### ISSUE TITLE
Functions/Test responsibilities 

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/2023-DSCI522-Group22#19]
Hey all, I'm writing my assigned tests/functions now.
We decided that I would create functions for the EDA part of our project.
I wanted to double check that there was no overlap with anyone else's work.

The visualizations of the histograms, bar charts ands correlation plot for the EDA is one area I'm concerned might have overlapped.
I only loosely recall what yingzi was working on and that might be part of it?
Can anyone confirm? I'm working on the first part of EDA that's unambiguous while I wait.

I'll go ahead and do the work anyway if I don't hear back by early tomorrow.

**Comment by jinyz8888** [comment]
Hello Jordan, no overlap with my work. My function is create_wine_prediction_chart(), that is a function for our last plot ( the final plot :). So please go ahead.
