### ISSUE TITLE
Remember to populate the README.MD file

### ISSUE THREAD

**Issue by lichunubc** [UBC-MDS/2023-DSCI522-Group22#2]
As mentioned in Milestone 1 instruction, we need to should use proper grammar and full sentences in your README.MD Point form may occur, but should be less than 10% of your written documents.

This is the summary of our data project:

Our analysis aimed to develop a predictive model to distinguish between red and white wines based on various physicochemical properties. This study employed logistic regression, a model renowned for its balance between predictive power and interpretability.

The regression result suggested that residual sugar and total sulfur dioxide had high positive coefficients, indicating a strong association with white wine, whereas density showed the most substantial negative impact, followed by alcohol and volatile acidity, suggesting these are key indicators of red wine.

The logistic regression model not only achieved high accuracy but also provided valuable insights into the features most indicative of wine type. This model can assist vintners in quality control and classification tasks. Moreover, the interpretability of the model offers a foundation for further research into wine composition and its impact on sensory attributes. Future studies might explore more complex models or delve deeper into feature engineering to enhance predictive accuracy and understanding.

**Comment by jinyz8888** [comment]
Thanks to Chun Li. This is an awesome summary of our project. Because we'll use the project name in Contributing.md, can we name our project as "Predcition on wine types"?
