### ISSUE TITLE
Next step to complete our project

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/2023-DSCI522-Group22#25]
Ok, I just pull requested the tests/functions for my part. This will complete the modularization part of our project.

Tomorrow we need to double check things (verify .yaml versions are correct , everyone's tests pass)
, make sure we've published the container image on DockerHub and publish the final report from the readme.

Good work team!

**Comment by jinyz8888** [comment]
I just updated my tests/function part. Need someone to merge it :)

**Comment by lichunubc** [comment]
A new post was made to specifically address works for Milestone. This post can be closed.
