### ISSUE TITLE
To do list for Milestone 3

### ISSUE THREAD

**Issue by lichunubc** [UBC-MDS/2023-DSCI522-Group22#31]
Here's a non-exhaustive to do list for this week's group project, based on the differences between our current repo and the sample repo from Tiffany.

1. Produce a rendered final report in html without any codes explicitly displayed to the audiences. The report should have built-in references to figures and bibliographies powered by Jupyter book.
2. Create a new "Result" folder to house figures (in PNG), models (pipelines and preprocessors, in pickle), and tables (in csv).
3. Create a new "Script" folder to house all updated .py files (ones we made last week) with the formats and features Tiffany demonstrated in Lecture 5.
4. Update the computational environment if additional libraries need to be installed.
5. Update the README.md file to reflect all the new changes.
6. ...

**Comment by lichunubc** [comment]
I am working on writing a script which will load the data, process the data and generate the confusion matrix

**Comment by jinyz8888** [comment]
I am working on download data file, unzip it and store csv into the destination folder
