### ISSUE TITLE
Question about current pull request 

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/2023-DSCI522-Group22#37]
I see that in the most recent pull request we are changing the helper function in addition to the main analyses code. Just trying to  make sure everything runs because the our last submission for milestone some of the test functions didn't run because of the changes in helper function.

**Comment by jcairn02** [comment]
I replied in the pull request dialogue. No helper functions were changed, it was the psycache, it was only a few bytes and I have no idea what that is or why it was changed.
