### ISSUE TITLE
finished rough draft of script, need to collaborate to progress

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/2023-DSCI522-Group22#40]
This is mostly directed to chun li. 
When you are finished your script let me know , so I can see if I need to add more function to my script? I made an educated guess everything my script was supposed to include, but not 100% confident.

**Comment by chrisgqy** [comment]
Okay sounds good. I am currently working on it.

**Comment by lichunubc** [comment]
Hi Jordan, I am still working on my part too. You can test your script with a sample dataframe to see if the expected PNG file will be produced or not
