### ISSUE TITLE
Weird format for combined data file

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/2023-DSCI522-Group22#41]
I tried to combine wineread.csv and winewhite.csv to be a single csv file. The code for it is: `# Read the CSV files
    df1 = pd.read_csv(file1, delimiter=';')
    df2 = pd.read_csv(file2, delimiter=';', header=None)

    # Concatenate the dataframes
    combined_df = pd.concat([df1, df2])`

However, the combined file looks weird. Can anyone tell me how to fix it?
<img width="980" alt="Screenshot 2023-12-02 at 8 38 18 AM" src="https://github.com/UBC-MDS/2023-DSCI522-Group22/assets/108684429/21c89c2f-573f-4e6c-83ef-6af774cf113d">

**Comment by jinyz8888** [comment]
I tried both axis=1 and axis=0, no one works. I also reset the index, also doesn't work. Really weird and stuck here.

**Comment by chrisgqy** [comment]
Maybe try this : pd.concat([df_white, df_red], ignore_index=True)

**Comment by lichunubc** [comment]
Do not use header=None

**Comment by jinyz8888** [comment]
solved
