### ISSUE TITLE
Overloading Issue

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/2023-DSCI522-Group22#42]
Hey guys, I am writing the scripts for the EDA and I find this step might be a bit overloading. This scripts require to read in 8 strings, which I think would be super inconvenient when we are actually use it in the terminal commands. I am thinking to breakdown into two parts:
 1. Basic Data Wrangling: where we a) read in the downloaded datasets(2 of them),b) concatenate them together, c) save the concatenated output, d) train test split them e) save train and test df locally
        - This requires five strings  as inputs when we use terminal command
        
 2. EDA: where all the graphing happens  
        - This requtires three strings as inputs when we use terminal command 
If no one has other opinion, I'll just continue on this

**Comment by chrisgqy** [comment]
Okay I am almost finished writing the scripts. After uploading them you can take a look and see how does that collaborate with your test function?

**Comment by lichunubc** [comment]
I agree with your design.

**Comment by chrisgqy** [comment]
Okay the updated results are in the pull requests. Could someone please merge it?

**Comment by lichunubc** [comment]
Approved and merged.
