### ISSUE TITLE
Update of env yml and docker

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/2023-DSCI522-Group22#44]
I forgot to update the docker file and yml file with new package: "click". Could someone approve my pull request and then perhaps add that? Thank you in advance :)

**Comment by jcairn02** [comment]
approved your pull request and modified the yaml to include click.
Figured I'd wait on changing the dockerfile as changing it triggers a push to dockerhub and It's likely we are going to make other modifications today.
