### ISSUE TITLE
Rough draft of scripts finished - Next steps

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/2023-DSCI522-Group22#52]
Ok, all the scripts/tables/figures are uploaded. My branch is pending merge.
Next major steps:

1. Bug fixing - someone run each script on their machine to see if it's reproducible
2. Modify our report to eliminate code and reference the tables/graphs in our repo.
3. More (see other github issues) :smile:

I'm reasonably confident I can do a good job of the second task, so unless there's objections I'll work on that now.

**Comment by jcairn02** [comment]
I've been working on understanding how to build the jupyter book report. Working on the build_jupyter_book branch.
Working on the second step of building our report as I mentioned

**Comment by jinyz8888** [comment]
Great! Thank you so much!
