### ISSUE TITLE
Runtime Error for eda.py

### ISSUE THREAD

**Issue by jinyz8888** [UBC-MDS/2023-DSCI522-Group22#64]
When I run the script, it gave me the following error, please check it:
`
<img width="1173" alt="image" src="https://github.com/UBC-MDS/2023-DSCI522-Group22/assets/108684429/f21b7748-6ef6-40b8-80e9-1f60a64775d5">
`

**Comment by jinyz8888** [comment]
<img width="1173" alt="Screenshot 2023-12-04 at 5 35 16 PM" src="https://github.com/UBC-MDS/2023-DSCI522-Group22/assets/108684429/8f324729-7c20-40b7-b586-a499ddf03f9e">

**Comment by lichunubc** [comment]
This issue has been resolved.
