### ISSUE TITLE
Book is fully rendered properly

### ISSUE THREAD

**Issue by jcairn02** [UBC-MDS/2023-DSCI522-Group22#70]
pre-emptively anticipating feedback, on Monday I got our github pages to render our report.
Today and tomorrow I'm dividng my attention between 573 and 522. I'll create the changelog and get onto fixing some of the suggestions.

I'm a little confused why group feedback isn't in our issues? I must have misinterpreted the instructions about the location.
I'll figure it out in 522 lecture today, I'll ask Tiff/TA.

**Comment by lichunubc** [comment]
Resolved by Jordan in PR #79
