### ISSUE TITLE
Workflow to populate the Docker File

### ISSUE THREAD

**Issue by lichunubc** [UBC-MDS/2023-DSCI522-Group22#9]
Based on our prior agreement, in order to allow each member to have a chance to add a few lines to the Docker File, we will have to make 4 branches and 4 Pull Requests, which seems tedious based on something that is trivial. How about we just make the changes on the Main branch instead only for this task?

**Comment by jinyz8888** [comment]
I agree.

**Comment by jcairn02** [comment]
I was just about to ask you in person about this exact idea lol. 
I'm not sure?
I think the intention of the workflow would be to develop good practises that can scale if we were working on a more complicated project. 
I agree creating extra branches feels unnecessary here, but perhaps we should just do it anyway?

Happy to vote on it haha

**Comment by lichunubc** [comment]
> I was just about to ask you in person about this exact idea lol. I'm not sure? I think the intention of the workflow would be to develop good practises that can scale if we were working on a more complicated project. I agree creating extra branches feels unnecessary here, but perhaps we should just do it anyway?
> 
> Happy to vote on it haha

In most of cases, we want to open a new branch to implement and test new features before merging them to main. In rare cases, if the change is very small, such as fixing a typo or adding a line or two for something trivial, we could just make changes on main branch directly

**Comment by jcairn02** [comment]
ok! makes sense. im on board
